# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HazardsFinder.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(1205, 791)
        widget.setStyleSheet("background-color:#D9F6CF")
        self.frame_3 = QtWidgets.QFrame(widget)
        self.frame_3.setGeometry(QtCore.QRect(20, 10, 1171, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(0, 0, 1171, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("color:rgb(0, 0, 255)")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(widget)
        self.frame.setGeometry(QtCore.QRect(20, 50, 1171, 731))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(10, 10, 501, 711))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(9, 10, 481, 311))
        self.frame_4.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 170, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"color:rgb(0, 0, 255);\n"
"border: none;")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        self.pushButton.setGeometry(QtCore.QRect(340, 10, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"color:rgb(255, 255, 255);\n"
"border-style: outset; \n"
"border: none;\n"
"border-radius:10px;\n"
"border-width: 2px; /* 设置边框宽度 */\n"
"QPushButton {\n"
"    : outset;\n"
"    border-width: 2px;\n"
"    background-color: rgb(0, 170, 0); \n"
"    padding: 5px; \n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset; }\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 110, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 85, 0);\n"
"border: none;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setGeometry(QtCore.QRect(10, 80, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border: none;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setGeometry(QtCore.QRect(10, 120, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border: none;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        self.label_7.setGeometry(QtCore.QRect(210, 80, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border: none;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_4)
        self.label_8.setGeometry(QtCore.QRect(210, 120, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border: none;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit.setGeometry(QtCore.QRect(130, 80, 61, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_2.setGeometry(QtCore.QRect(130, 120, 61, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_3.setGeometry(QtCore.QRect(330, 120, 61, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_4.setGeometry(QtCore.QRect(330, 80, 61, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_5.setGeometry(QtCore.QRect(410, 100, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"color:rgb(255, 255, 255);\n"
"border-style: outset; \n"
"border: none;\n"
"border-radius:10px;\n"
"border-width: 2px; /* 设置边框宽度 */\n"
"QPushButton {\n"
"    : outset;\n"
"    border-width: 2px;\n"
"    background-color: rgb(0, 170, 0); \n"
"    padding: 5px; \n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset; }\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        self.label_9.setGeometry(QtCore.QRect(10, 150, 244, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(0, 85, 0);\n"
"border: none;")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_4)
        self.label_10.setGeometry(QtCore.QRect(10, 180, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border: none;")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_4)
        self.label_11.setGeometry(QtCore.QRect(10, 220, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border: none;")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_5.setGeometry(QtCore.QRect(130, 180, 61, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_6.setGeometry(QtCore.QRect(130, 220, 61, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_12 = QtWidgets.QLabel(self.frame_4)
        self.label_12.setGeometry(QtCore.QRect(210, 180, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border: none;")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_4)
        self.label_13.setGeometry(QtCore.QRect(210, 220, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border: none;")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_7.setGeometry(QtCore.QRect(330, 180, 61, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_8.setGeometry(QtCore.QRect(330, 220, 61, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_6.setGeometry(QtCore.QRect(410, 210, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"color:rgb(255, 255, 255);\n"
"border-style: outset; \n"
"border: none;\n"
"border-radius:10px;\n"
"border-width: 2px; /* 设置边框宽度 */\n"
"QPushButton {\n"
"    : outset;\n"
"    border-width: 2px;\n"
"    background-color: rgb(0, 170, 0); \n"
"    padding: 5px; \n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset; }\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_14 = QtWidgets.QLabel(self.frame_4)
        self.label_14.setGeometry(QtCore.QRect(210, 260, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border: none;")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_9.setGeometry(QtCore.QRect(330, 260, 61, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_15 = QtWidgets.QLabel(self.frame_4)
        self.label_15.setGeometry(QtCore.QRect(400, 270, 75, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(0, 0, 0);\n"
"border: none;")
        self.label_15.setObjectName("label_15")
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setGeometry(QtCore.QRect(10, 330, 481, 371))
        self.frame_6.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 170, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"color:rgb(0, 0, 255);\n"
"border: none;")
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 10, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"color:rgb(255, 255, 255);\n"
"border-style: outset; \n"
"border: none;\n"
"border-radius:10px;\n"
"border-width: 2px; /* 设置边框宽度 */\n"
"QPushButton {\n"
"    : outset;\n"
"    border-width: 2px;\n"
"    background-color: rgb(0, 170, 0); \n"
"    padding: 5px; \n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset; }\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_4.setGeometry(QtCore.QRect(340, 10, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"color:rgb(255, 255, 255);\n"
"border-style: outset; \n"
"border: none;\n"
"border-radius:10px;\n"
"border-width: 2px; /* 设置边框宽度 */\n"
"QPushButton {\n"
"    : outset;\n"
"    border-width: 2px;\n"
"    background-color: rgb(0, 170, 0); \n"
"    padding: 5px; \n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset; }\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_16 = QtWidgets.QLabel(self.frame_6)
        self.label_16.setGeometry(QtCore.QRect(10, 50, 110, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(0, 85, 0);\n"
"border: none;")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame_6)
        self.label_17.setGeometry(QtCore.QRect(10, 80, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border: none;")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_10.setGeometry(QtCore.QRect(130, 80, 61, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_18 = QtWidgets.QLabel(self.frame_6)
        self.label_18.setGeometry(QtCore.QRect(210, 80, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border: none;")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_11.setGeometry(QtCore.QRect(330, 80, 61, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_19 = QtWidgets.QLabel(self.frame_6)
        self.label_19.setGeometry(QtCore.QRect(10, 120, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border: none;")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_12.setGeometry(QtCore.QRect(130, 120, 61, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_20 = QtWidgets.QLabel(self.frame_6)
        self.label_20.setGeometry(QtCore.QRect(210, 120, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border: none;")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_13.setGeometry(QtCore.QRect(330, 120, 61, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_7.setGeometry(QtCore.QRect(410, 100, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"color:rgb(255, 255, 255);\n"
"border-style: outset; \n"
"border: none;\n"
"border-radius:10px;\n"
"border-width: 2px; /* 设置边框宽度 */\n"
"QPushButton {\n"
"    : outset;\n"
"    border-width: 2px;\n"
"    background-color: rgb(0, 170, 0); \n"
"    padding: 5px; \n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset; }\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_21 = QtWidgets.QLabel(self.frame_6)
        self.label_21.setGeometry(QtCore.QRect(10, 160, 110, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(0, 85, 0);\n"
"border: none;")
        self.label_21.setObjectName("label_21")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_9.setGeometry(QtCore.QRect(410, 310, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"color:rgb(255, 255, 255);\n"
"border-style: outset; \n"
"border: none;\n"
"border-radius:10px;\n"
"border-width: 2px; /* 设置边框宽度 */\n"
"QPushButton {\n"
"    : outset;\n"
"    border-width: 2px;\n"
"    background-color: rgb(0, 170, 0); \n"
"    padding: 5px; \n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset; }\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_22 = QtWidgets.QLabel(self.frame_6)
        self.label_22.setGeometry(QtCore.QRect(270, 220, 121, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border: none;")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.frame_6)
        self.label_23.setGeometry(QtCore.QRect(270, 260, 121, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border: none;")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_14.setGeometry(QtCore.QRect(400, 220, 61, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_15.setGeometry(QtCore.QRect(400, 260, 61, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_15.setFont(font)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.frame_6)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 190, 231, 171))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setGeometry(QtCore.QRect(530, 10, 631, 321))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.frame_5.setFont(font)
        self.frame_5.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 10, 165, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"color:rgb(255, 255, 255);\n"
"border-style: outset; \n"
"border: none;\n"
"border-radius:10px;\n"
"border-width: 2px; /* 设置边框宽度 */\n"
"QPushButton {\n"
"    : outset;\n"
"    border-width: 2px;\n"
"    background-color: rgb(0, 170, 0); \n"
"    padding: 5px; \n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"color:rgb(255, 255, 255); }\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_5)
        self.tableWidget.setGeometry(QtCore.QRect(10, 51, 611, 261))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setGeometry(QtCore.QRect(530, 340, 631, 381))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.frame_8.setFont(font)
        self.frame_8.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_11.setGeometry(QtCore.QRect(290, 10, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"color:rgb(255, 255, 255);\n"
"border-style: outset; \n"
"border: none;\n"
"border-radius:10px;\n"
"border-width: 2px; /* 设置边框宽度 */\n"
"QPushButton {\n"
"    : outset;\n"
"    border-width: 2px;\n"
"    background-color: rgb(0, 170, 0); \n"
"    padding: 5px; \n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset; }\n"
"")
        self.pushButton_11.setObjectName("pushButton_11")
        self.label_24 = QtWidgets.QLabel(self.frame_8)
        self.label_24.setGeometry(QtCore.QRect(440, 10, 101, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border: none;")
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_16.setGeometry(QtCore.QRect(550, 10, 61, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_16.setFont(font)
        self.lineEdit_16.setStyleSheet("QLineEdit {\n"
"    border: 1px solid rgb(0, 0, 0); \n"
"}")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_12.setGeometry(QtCore.QRect(30, 10, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"color:rgb(255, 255, 255);\n"
"border-style: outset; \n"
"border: none;\n"
"border-radius:10px;\n"
"border-width: 2px; /* 设置边框宽度 */\n"
"QPushButton {\n"
"    : outset;\n"
"    border-width: 2px;\n"
"    background-color: rgb(0, 170, 0); \n"
"    padding: 5px; \n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset; }\n"
"")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_13.setGeometry(QtCore.QRect(160, 10, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"color:rgb(255, 255, 255);\n"
"border-style: outset; \n"
"border: none;\n"
"border-radius:10px;\n"
"border-width: 2px; /* 设置边框宽度 */\n"
"QPushButton {\n"
"    : outset;\n"
"    border-width: 2px;\n"
"    background-color: rgb(0, 170, 0); \n"
"    padding: 5px; \n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset; }\n"
"")
        self.pushButton_13.setObjectName("pushButton_13")
        self.graphicsView = QtWidgets.QGraphicsView(self.frame_8)
        self.graphicsView.setGeometry(QtCore.QRect(10, 42, 305, 330))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        self.graphicsView.setFont(font)
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.frame_8)
        self.graphicsView_2.setGeometry(QtCore.QRect(316, 42, 305, 330))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        self.graphicsView_2.setFont(font)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setGeometry(QtCore.QRect(313, 43, 4, 328))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "HazardsFinder"))
        self.label.setText(_translate("widget", "Suspect and nontarget screening system for pesticides, veterinary drugs, and their transformation products in food"))
        self.label_2.setText(_translate("widget", "Suspect screening"))
        self.pushButton.setText(_translate("widget", "Upload samples"))
        self.label_4.setText(_translate("widget", "Exp. MS/MS"))
        self.label_5.setText(_translate("widget", "Mass error/ppm"))
        self.label_6.setText(_translate("widget", "Δ RT/min"))
        self.label_7.setText(_translate("widget", "Isotope pattern"))
        self.label_8.setText(_translate("widget", "MS2 score"))
        self.pushButton_5.setText(_translate("widget", "Run"))
        self.label_9.setText(_translate("widget", "Public MS/MS (online or literature)"))
        self.label_10.setText(_translate("widget", "Mass error/ppm"))
        self.label_11.setText(_translate("widget", "Δ RT/min"))
        self.label_12.setText(_translate("widget", "Isotope pattern"))
        self.label_13.setText(_translate("widget", "MS2 score"))
        self.pushButton_6.setText(_translate("widget", "Run"))
        self.label_14.setText(_translate("widget", "Frag. Num."))
        self.label_15.setText(_translate("widget", "for literature"))
        self.label_3.setText(_translate("widget", "Nontarget screening"))
        self.pushButton_3.setText(_translate("widget", "Upload samples"))
        self.pushButton_4.setText(_translate("widget", "Upload peaks"))
        self.label_16.setText(_translate("widget", "TP matching"))
        self.label_17.setText(_translate("widget", "Mass error/ppm"))
        self.label_18.setText(_translate("widget", "Isotope pattern"))
        self.label_19.setText(_translate("widget", "Δ RT/min"))
        self.label_20.setText(_translate("widget", "Frag. Num."))
        self.pushButton_7.setText(_translate("widget", "Run"))
        self.label_21.setText(_translate("widget", "CFI matching"))
        self.pushButton_9.setText(_translate("widget", "Run"))
        self.label_22.setText(_translate("widget", "MS/MS error/ppm"))
        self.label_23.setText(_translate("widget", "MS/MS inten filter"))
        self.pushButton_2.setText(_translate("widget", "Result loading"))
        self.pushButton_11.setText(_translate("widget", "Export"))
        self.label_24.setText(_translate("widget", "manual check"))
        self.pushButton_12.setText(_translate("widget", "< Last"))
        self.pushButton_13.setText(_translate("widget", "> Next"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widget = QtWidgets.QWidget()
    ui = Ui_widget()
    ui.setupUi(widget)
    widget.show()
    sys.exit(app.exec_())
